hid_engine.c File Reference
hid_engine.c File Reference
Detailed Description
HID Engine for the HIDI2C Specification.
This file is responsible for the HID level of the HIDI2C engine. All of the descriptors are managed here and commands/data are processed from the I2C layer. The goal of this layer is to abstract out the I2C/Communication layer. Relevant functions that communicate with the I2C layer are declared external and leave the programmer with the liberty of using their own I2C communication method.
Sending HIDI2C reports over multiple physical interfaces in parallel is also supported. This is accomplished by use of an interface parameter for API calls. This interface parameter is interface implementation specific and is defined in the hidi2c_settings.h file.
#include <hid_engine.h>
#include <hidi2c_errno.h>
#include <hidi2c_settings.h>
#include <hid_reportparser.h>
#include <i2c_engine_usci.h>
#include <i2c_engine_usci_init.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
Functions
int getIndexForInterface (uint8_t interface)
BOOL handleHIDCommand (uint8_t interface, uint8_t *data)
uint8_t * hidI2C_getNextQueuedData (uint8_t inf)
void setGPIOPinActive (uint8_t interface)
BOOL outputReportEventHandler (uint8_t interface, uint8_t *data)
BOOL goToSleepEventHandler ()
BOOL wakeUpEventHandler ()
BOOL handleSetReportCalled (uint8_t interface, uint8_t reportid, uint8_t *feature)
uint8_t * handleGetReportCalled (uint8_t interface, uint8_t reportid)
BOOL initializeHidI2CStack (tHidI2CSetting *settings, uint8_t numOfInstances)
BOOL initializeHidI2CStackIdle (tHidI2CSetting *settings, uint8_t numOfInstances, BOOL idle)
void hidI2C_setNextQueuedData (uint8_t inf)
BOOL hidI2C_haveMoreGPIOsPending (uint8_t inf)
void setFeatureReport (uint8_t interface, uint8_t *report)
uint8_t setInputReportAndInitiateSend (uint8_t interface, uint8_t *report)
void hidI2C_handleRegisterPointer (uint8_t interface, uint16_t currentRegisterIndex)
BOOL hidI2C_handleData (uint8_t interface, uint8_t *data, uint16_t reg)
void queueResetReport (uint8_t interface)
Variables
uint8_t * inputReportQueue [SIZE_OF_INPUT_QUEUE]
tHidI2CInterface * interfaces
int flip = 0
Function Documentation
int getIndexForInterface (uint8_t interface)
Finds the index of the physical interfaces in the interfaces array.
Parameters
rid The interface to find the index of. Returns -1 if not found.
Returns
The index of the interface in interfaces
Referenced by handleHIDCommand(), hidI2C_handleData(), hidI2C_handleRegisterPointer(), hidI2C_haveMoreGPIOsPending(), hidI2C_setNextQueuedData(), queueResetReport(), setFeatureReport(), and setInputReportAndInitiateSend().
BOOL handleHIDCommand (uint8_t interface, uint8_t * data)
Internal function that takes a command and decodes/processes the command. Currently, only the mandatory class commands for HIDI2C devices are implemented.
Parameters
interface Specific interface to handle the command for
data Data for the command to handle
References bitSwap(), HidI2CInterface::curOpCode, HidI2CInterface::currentQueuePos, HidI2CInterface::dataRegister, FALSE, sReportIdNode::featureSize, getIndexForInterface(), goToSleepEventHandler(), handleGetReportCalled(), handleSetReportCalled(), HID_GET_IDLE, HID_GET_PROTOCOL, HID_GET_REPORT, HID_RESET, HID_SET_IDLE, HID_SET_POWER, HID_SET_PROTOCOL, HID_SET_REPORT, hidI2C_enableInterrupts(), hidI2C_setDataWithoutInterrupt(), index, HidI2CInterface::info, INPUT_REPORT_TYPE, HidI2CInterface::inputOffset, sReportIdNode::inSize, OUTPUT_REPORT_TYPE, outputReportEventHandler(), queueResetReport(), sReportDescriptorInformation::reportIDs, HidI2CInterface::sizeOfDataReg, and wakeUpEventHandler().
Referenced by hidI2C_handleData().
uint8_t* hidI2C_getNextQueuedData (uint8_t inf)
void setGPIOPinActive (uint8_t interface)
BOOL outputReportEventHandler (uint8_t interface, uint8_t * data)
Event handler propagated from the HIDI2C API. With this function, the host has sent an output report (the HOST wants to write to the DEVICE). The output report is in standard HID Output Report format as specified by the HID Spec.
For variables with multiple top level collections:
<ul><li>Report ID (1 Bytes) + Report (Variable)</ul>
For variables with only one top level collection and no report ID:
<ul><li>Report (variable)</ul>
Parameters
interface Interface from where the output report originated
data Pointer to output report
Output report handler.
Returns
TRUE if the user wants to clear LPM bits after this interrupt, FALSE if the user wants the LPM bits not to be touched \
References FALSE.
Referenced by handleHIDCommand(), and hidI2C_handleData().
BOOL goToSleepEventHandler ()
Event handler that are called when the host receives a command to put the device to sleep or wake it up. It is important to note that these handlers are called in interrupt context and should be very brief in nature (set a flag
Returns
TRUE if the user wants to clear LPM bits after this interrupt, FALSE if the user wants the LPM bits not to be touched
Event handlers that are called when the host receives a command to put the device to sleep or wake it up. It is important to note that these handlers are called in interrupt context and should be very brief in nature (set a flag
Returns
TRUE if the user wants to clear LPM bits after this interrupt, FALSE if the user wants the LPM bits not to be touched
References gotoSleep, and TRUE.
Referenced by handleHIDCommand().
BOOL wakeUpEventHandler ()
Because LPM bits need to be cleared at the end of the calling interrupt. Returning TRUE from this function will clear the LPM bits on the MSP430 and cause it to wake up from sleep.
Returns
TRUE if the user wants to clear LPM bits after this interrupt, FALSE if the user wants the LPM bits not to be touched
References FALSE, gotoSleep, and TRUE.
Referenced by handleHIDCommand().
BOOL handleSetReportCalled (uint8_t interface, uint8_t reportid, uint8_t * feature)
Event handler called when a SET_REPORT command is issued by the host. For keyboards/mice, feature reports are not supported so this is a dummy handler
Parameters
interface Specific interface being used
reportid Report ID of the feature report that was set
feature New feature report
Returns
TRUE if the user wants to clear LPM bits after this interrupt, FALSE if the user wants the LPM bits not to be touched
References FALSE.
Referenced by handleHIDCommand().
uint8_t* handleGetReportCalled (uint8_t interface, uint8_t reportid)
Grabs the latest input report from the device.
Returns
uint8_t* Pointer to array with the latest input report.
References inputReport, and mouseReport.
Referenced by handleHIDCommand().
BOOL initializeHidI2CStack (tHidI2CSetting * settings, uint8_t numOfInstances)
Initializes the HIDI2C Stack. This setting initializes both the I2C and HID layer of the stack. Memory allocation and initialization of the HID descriptor is done within this function. The give report descriptor is automatically parsed and the maximum sizes are automatically calculated. Support for multiple HID TLCs is also supported and calculated from the report descriptor parser function.
Each interface provided will allocate its own set of registers and memory space. This allows for devices that have multiple interfaces (and larger memory spaces) to send out multiple HIDI2C packets in parallel.
Parameters
settings Pointer to an array of HIDI2C settings. This data structure is a list of all the physical interfaces as well as the report descriptor that is associated with that specific interface.
numOfInstances Number of interfaces that are included within the settings array.
References FALSE, and initializeHidI2CStackIdle().
Referenced by main().
BOOL initializeHidI2CStackIdle (tHidI2CSetting * settings, uint8_t numOfInstances, BOOL idle)
References HidDescriptor::bcdVersion_H, HidDescriptor::bcdVersion_L, HidI2CSetting::bInterface, HidI2CInterface::bInterface, sReportDescriptorInformation::bMaxInputSize, sReportDescriptorInformation::bMaxOutputSize, sReportDescriptorInformation::bNumOfReportIDs, HidI2CInterface::curOpCode, HidI2CInterface::currentQueuePos, HidI2CInterface::dataRegister, HidI2CInterface::featureReports, HidI2CInterface::featureReportsDefault, sReportIdNode::featureSize, getReportInformation(), HID_COMMAND_REG, HID_DATA_REG, HID_INPUT_REPORT_REG, HID_OUTPUT_REPORT_REG, HID_REPORT_DESC_REG, HidI2CInterface::hidDescriptor, hidI2C_initializeI2C(), HIDI2C_NO_MEMORY, HIDI2C_SUCCESS, HidI2CInterface::info, HidI2CInterface::inputOffset, inputReportQueue, HidI2CInterface::inputReportQueue, HidI2CInterface::inputReportRegister, sReportIdNode::inSize, HidI2CInterface::numOfReportIDs, HidI2CInterface::outputReportRegister, HidI2CSetting::pReportDescriptor, PRODUCT_ID, HidI2CInterface::reportDescriptor, sReportDescriptorInformation::reportIDs, HidI2CInterface::resetRegister, SIZE_OF_INPUT_QUEUE, SIZEOF_HID_DESCRIPTOR, HidI2CInterface::sizeOfDataReg, VENDOR_ID, VERSION_ID, HidDescriptor::wCommandRegister, HidDescriptor::wDataRegister, HidDescriptor::wHIDDescLength, HidDescriptor::wInputRegister, HidDescriptor::wMaxInputLength, HidDescriptor::wMaxOutputLength, HidDescriptor::wOutputRegister, HidDescriptor::wProductID, HidDescriptor::wReportDescLength, HidDescriptor::wReportDescRegister, HidI2CSetting::wReportLength, HidDescriptor::wReserved0, HidDescriptor::wReserved1, HidDescriptor::wVendorID, and HidDescriptor::wVersionID.
Referenced by initializeHidI2CStack().
void hidI2C_setNextQueuedData (uint8_t inf)
Sets the next queued data on the device to be read for a device initiated transfer
References sReportDescriptorInformation::bMaxInputSize, HidI2CInterface::currentQueuePos, getIndexForInterface(), hidI2C_setDataAndInitializeInterrupt(), HidI2CInterface::info, HidI2CInterface::inputOffset, HidI2CInterface::inputReportQueue, and SIZE_OF_INPUT_QUEUE.
BOOL hidI2C_haveMoreGPIOsPending (uint8_t inf)
Function that returns true if there is another input report queued that needs to be sent to the host
References FALSE, getIndexForInterface(), and TRUE.
void setFeatureReport (uint8_t interface, uint8_t * report)
Sets a feature report in the HIDI2C API. If feature reports are used by the device, this function could be called in conjunction with the initializeHidI2CStackIdle command and an initial report should be passed to the API. This also sets the "default" featuyre report.
Parameters
interface I2C interface being used
report Feature report to send (include report ID if multiple TLCs are used.
References getIndexForInterface(), and index.
uint8_t setInputReportAndInitiateSend (uint8_t interface, uint8_t * report)
Sets an input report and initializes the send. Depending on if the user defined NON_BLOCKING_MODE has false in the hidi2c_settings.h file, this function will return HIDI2C_BUSY if there is a transfer in progress. If the is in blocking mode, interrupts will be disables and the function will wait for ending pending transfer to finish before scheduling the transfer and asserting the GPIO pin.
Parameters
interface Specific interface to send input report over
report Input report to set
Returns
HIDI2C_SUCCESS on successful copying of the provided report into the local input report register. See hidi2c_errno.h for other error codes.
References HidI2CInterface::currentQueuePos, getIndexForInterface(), hidI2C_disableInterrupts(), hidI2C_enableInterrupts(), HIDI2C_INVALID_REPORTID, HIDI2C_NO_MEMORY, hidI2C_setGPIOPinActive(), HIDI2C_SUCCESS, index, HidI2CInterface::info, inputReportQueue, HidI2CInterface::inputReportQueue, sReportIdNode::inSize, sReportDescriptorInformation::reportIDs, and SIZE_OF_INPUT_QUEUE.
Referenced by main(), and Port1_ISR().
void hidI2C_handleRegisterPointer (uint8_t interface, uint16_t currentRegisterIndex)
Provides the I2C layer with the necessary register pointer for the given index. This register can either be DATA, INPUT, OUTPUT, REPORT, or HID DESCRIPTOR.
Parameters
interface Specific interface that is requesting the data pointer
currentRegisterIndex Register index that the I2C layer needs the corresponding pointer for.
References FALSE, flip, getIndexForInterface(), HID_COMMAND_REG, HID_DATA_REG, HID_DESC_REG, HID_INPUT_REPORT_REG, HID_OUTPUT_REPORT_REG, HID_REPORT_DESC_REG, HID_RES_REG, hidI2C_enableInterrupts(), hidI2C_setDataWithoutInterrupt(), HidI2CInterface::inputOffset, HidI2CInterface::setReportCalled, and SIZEOF_HID_DESCRIPTOR.
BOOL hidI2C_handleData (uint8_t interface, uint8_t * data, uint16_t reg)
Handles data received from the I2C layer. When this function is called, data has been received and needs to be processed past the point of obtaining the register pointer. The three cases this can happen are: OUTPUT REPORT, HID COMMAND, and DATA COMMAND (for SET_REPORT)
Parameters
interface Specific interface to handle to data for
data Data received from the host
reg The current register index (either OUTPUT, COMMAND, or DATA)
References bitSwap(), HidI2CInterface::curOpCode, FALSE, getIndexForInterface(), handleHIDCommand(), HID_COMMAND_REG, HID_DATA_REG, HID_GET_REPORT, HID_OUTPUT_REPORT_REG, HID_RESET, HID_SET_POWER, HID_SET_REPORT, hidI2C_setDataChangeRegWithoutInterrupt(), hidI2C_setDataWithoutInterrupt(), outputReportEventHandler(), HidI2CInterface::setReportCalled, and TRUE.
void queueResetReport (uint8_t interface)
Queues a dummy "reset" report for the host to read. This can also be used as a device initiated reset to the host. The value of this report is a normal input report with a sentinel value of 0x0000 for the length.
References HidI2CInterface::currentQueuePos, getIndexForInterface(), hidI2C_setGPIOPinActive(), HidI2CInterface::inputOffset, and inputReportQueue.
Referenced by handleHIDCommand().
Variable Documentation
uint8_t* inputReportQueue[SIZE_OF_INPUT_QUEUE]
Referenced by initializeHidI2CStackIdle(), queueResetReport(), and setInputReportAndInitiateSend().
tHidI2CInterface* interfaces
int flip = 0
Referenced by hidI2C_handleRegisterPointer().
Copyright 2013, Texas Instruments Incorporated