i2c_engine_usci.c File Reference
i2c_engine_usci.c File Reference
Detailed Description
I2C (USCI Implementation) for HIDI2C Specification I2C engine for the HIDI2C implementation.
This is the transport layer of the API. In this implementation, USCI is used for management of the I2C. This layer is abstracted out so another implementation of I2C can be used.
GPIO ports and specific interface settings are defined in the hidi2c_settings.h file.
#include <msp430.h>
#include <hidi2c_settings.h>
#include <hidi2c_errno.h>
#include "hid_engine.h"
#include <i2c_engine_usci.h>
#include <i2c_engine_usci_init.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
Functions
BOOL hidI2C_handleData (uint8_t interface, uint8_t *data, uint16_t reg)
void hidI2C_handleRegisterPointer (uint8_t interface, uint16_t currentRegisterIndex)
void hidI2C_setNextQueuedData (uint8_t inf)
BOOL hidI2C_haveMoreGPIOsPending (uint8_t inf)
BOOL hidI2C_initializeI2C (BOOL idle)
uint8_t hidI2C_setDataAndInitializeInterrupt (uint8_t interface, uint8_t *data, uint16_t length)
uint8_t hidI2C_setDataWithoutInterrupt (uint8_t interface, uint8_t *data, uint16_t length)
uint8_t hidI2C_setDataChangeRegWithoutInterrupt (uint8_t interface, uint8_t *data, uint16_t length, uint16_t registerIndex)
BOOL hidI2C_isGPIOAsserted (uint8_t interface)
BOOL hidI2C_busyWithTransfer (uint8_t interface)
void hidI2C_disableInterrupts (uint8_t interface)
void hidI2C_enableInterrupts (uint8_t interface)
uint16_t bitSwap (uint8_t msb, uint8_t lsb)
Function Documentation
BOOL hidI2C_handleData (uint8_t interface, uint8_t * data, uint16_t reg)
Handles data received from the I2C layer. When this function is called, data has been received and needs to be processed past the point of obtaining the register pointer. The three cases this can happen are: OUTPUT REPORT, HID COMMAND, and DATA COMMAND (for SET_REPORT)
Parameters
interface Specific interface to handle to data for
data Data received from the host
reg The current register index (either OUTPUT, COMMAND, or DATA)
References bitSwap(), HidI2CInterface::curOpCode, FALSE, getIndexForInterface(), handleHIDCommand(), HID_COMMAND_REG, HID_DATA_REG, HID_GET_REPORT, HID_OUTPUT_REPORT_REG, HID_RESET, HID_SET_POWER, HID_SET_REPORT, hidI2C_setDataChangeRegWithoutInterrupt(), hidI2C_setDataWithoutInterrupt(), outputReportEventHandler(), HidI2CInterface::setReportCalled, and TRUE.
void hidI2C_handleRegisterPointer (uint8_t interface, uint16_t currentRegisterIndex)
Provides the I2C layer with the necessary register pointer for the given index. This register can either be DATA, INPUT, OUTPUT, REPORT, or HID DESCRIPTOR.
Parameters
interface Specific interface that is requesting the data pointer
currentRegisterIndex Register index that the I2C layer needs the corresponding pointer for.
References FALSE, flip, getIndexForInterface(), HID_COMMAND_REG, HID_DATA_REG, HID_DESC_REG, HID_INPUT_REPORT_REG, HID_OUTPUT_REPORT_REG, HID_REPORT_DESC_REG, HID_RES_REG, hidI2C_enableInterrupts(), hidI2C_setDataWithoutInterrupt(), HidI2CInterface::inputOffset, HidI2CInterface::setReportCalled, and SIZEOF_HID_DESCRIPTOR.
void hidI2C_setNextQueuedData (uint8_t inf)
Sets the next queued data on the device to be read for a device initiated transfer
References sReportDescriptorInformation::bMaxInputSize, HidI2CInterface::currentQueuePos, getIndexForInterface(), hidI2C_setDataAndInitializeInterrupt(), HidI2CInterface::info, HidI2CInterface::inputOffset, HidI2CInterface::inputReportQueue, and SIZE_OF_INPUT_QUEUE.
BOOL hidI2C_haveMoreGPIOsPending (uint8_t inf)
Function that returns true if there is another input report queued that needs to be sent to the host
References FALSE, getIndexForInterface(), and TRUE.
BOOL hidI2C_initializeI2C (BOOL idle)
Initializes the I2C physical layer of the HIDI2C API. ifdefs are used to minimize the memory footprint if the user is not using every interface.
Returns
TRUE if initialization succeeded. FALSE otherwise.
References FALSE, hidI2C_initializeUSCII2C(), and TRUE.
Referenced by initializeHidI2CStackIdle().
uint8_t hidI2C_setDataAndInitializeInterrupt (uint8_t interface, uint8_t * data, uint16_t length)
Internal API command to transfer data from the host and initialize interrupt. Checking for conflicts concurrent accesses is done in the HID layer.
Parameters
interface Specific USCI module to send data over. Defined in the hidi2c_settings.h file.
data Pointer to data to "queue" for transfer.
References hidI2C_setGPIOPinActive(), HIDI2C_SUCCESS, and USCIB0.
Referenced by hidI2C_setNextQueuedData().
uint8_t hidI2C_setDataWithoutInterrupt (uint8_t interface, uint8_t * data, uint16_t length)
Function that sets the current data pointer without changing the register value.
References hidI2C_setDataChangeRegWithoutInterrupt().
Referenced by handleHIDCommand(), hidI2C_handleData(), and hidI2C_handleRegisterPointer().
uint8_t hidI2C_setDataChangeRegWithoutInterrupt (uint8_t interface, uint8_t * data, uint16_t length, uint16_t registerIndex)
Internal API command to transfer data from the host without interrupt.
Parameters
interface Specific USCI module to send data over. Defined in the hidi2c_settings.h file.
data Pointer to data to "queue" for transfer.
References HIDI2C_SUCCESS, and USCIB0.
Referenced by hidI2C_handleData(), and hidI2C_setDataWithoutInterrupt().
BOOL hidI2C_isGPIOAsserted (uint8_t interface)
Returns true if the GPIO is asserted for the given interface.
References FALSE, USCIB0, USCIB0_GPIO_PDIR, and USCIB0_GPIO_PIN.
BOOL hidI2C_busyWithTransfer (uint8_t interface)
Function that returns true if there is a transfer in progress on given interface
Parameters
interface Specific USCI module to send data over. Defined in the hidi2c_settings.h file.
Returns
TRUE if a transfer is in progress, false otherwise.
References FALSE, and USCIB0.
void hidI2C_disableInterrupts (uint8_t interface)
Disables START interrupts from happening on given interface.
Parameters
interface Specific USCI module to send data over. Defined in the hidi2c_settings.h file.
References USCIB0.
Referenced by setInputReportAndInitiateSend().
void hidI2C_enableInterrupts (uint8_t interface)
Allows START interrupts to happen on given interface
Parameters
interface Specific USCI module to send data over. Defined in the hidi2c_settings.h file.
References USCIB0.
Referenced by handleHIDCommand(), hidI2C_handleRegisterPointer(), and setInputReportAndInitiateSend().
uint16_t bitSwap (uint8_t msb, uint8_t lsb)
Simple function to take two bytes and combine them into one word. This is useful for HIDI2C because everything comes in from the host MSB first
Parameters
msb Most significant byte of data
lsb Least significant byte of data
Referenced by handleHIDCommand(), and hidI2C_handleData().
Copyright 2013, Texas Instruments Incorporated