i2c_engine_usci.h File Reference
i2c_engine_usci.h File Reference
#include <hidi2c_types.h>
Functions
BOOL hidI2C_initializeI2C (BOOL idle)
uint8_t hidI2C_setDataAndInitializeInterrupt (uint8_t interface, uint8_t *data, uint16_t length)
uint8_t hidI2C_setDataWithoutInterrupt (uint8_t interface, uint8_t *data, uint16_t length)
uint8_t hidI2C_setDataChangeRegWithoutInterrupt (uint8_t interface, uint8_t *data, uint16_t length, uint16_t registerIndex)
BOOL hidI2C_isGPIOAsserted (uint8_t interface)
void hidI2C_disableInterrupts (uint8_t interface)
void hidI2C_enableInterrupts (uint8_t interface)
BOOL hidI2C_busyWithTransfer (uint8_t interface)
uint16_t bitSwap (uint8_t lsb, uint8_t msb)
Function Documentation
BOOL hidI2C_initializeI2C (BOOL idle)
Initializes the I2C physical layer of the HIDI2C API. ifdefs are used to minimize the memory footprint if the user is not using every interface.
Returns
TRUE if initialization succeeded. FALSE otherwise.
References FALSE, hidI2C_initializeUSCII2C(), and TRUE.
Referenced by initializeHidI2CStackIdle().
uint8_t hidI2C_setDataAndInitializeInterrupt (uint8_t interface, uint8_t * data, uint16_t length)
Internal API command to transfer data from the host and initialize interrupt. Checking for conflicts concurrent accesses is done in the HID layer.
Parameters
interface Specific USCI module to send data over. Defined in the hidi2c_settings.h file.
data Pointer to data to "queue" for transfer.
References hidI2C_setGPIOPinActive(), HIDI2C_SUCCESS, and USCIB0.
Referenced by hidI2C_setNextQueuedData().
uint8_t hidI2C_setDataWithoutInterrupt (uint8_t interface, uint8_t * data, uint16_t length)
Function that sets the current data pointer without changing the register value.
References hidI2C_setDataChangeRegWithoutInterrupt().
Referenced by handleHIDCommand(), hidI2C_handleData(), and hidI2C_handleRegisterPointer().
uint8_t hidI2C_setDataChangeRegWithoutInterrupt (uint8_t interface, uint8_t * data, uint16_t length, uint16_t registerIndex)
Internal API command to transfer data from the host without interrupt.
Parameters
interface Specific USCI module to send data over. Defined in the hidi2c_settings.h file.
data Pointer to data to "queue" for transfer.
References HIDI2C_SUCCESS, and USCIB0.
Referenced by hidI2C_handleData(), and hidI2C_setDataWithoutInterrupt().
BOOL hidI2C_isGPIOAsserted (uint8_t interface)
Returns true if the GPIO is asserted for the given interface.
References FALSE, USCIB0, USCIB0_GPIO_PDIR, and USCIB0_GPIO_PIN.
void hidI2C_disableInterrupts (uint8_t interface)
Disables START interrupts from happening on given interface.
Parameters
interface Specific USCI module to send data over. Defined in the hidi2c_settings.h file.
References USCIB0.
Referenced by setInputReportAndInitiateSend().
void hidI2C_enableInterrupts (uint8_t interface)
Allows START interrupts to happen on given interface
Parameters
interface Specific USCI module to send data over. Defined in the hidi2c_settings.h file.
References USCIB0.
Referenced by handleHIDCommand(), hidI2C_handleRegisterPointer(), and setInputReportAndInitiateSend().
BOOL hidI2C_busyWithTransfer (uint8_t interface)
Function that returns true if there is a transfer in progress on given interface
Parameters
interface Specific USCI module to send data over. Defined in the hidi2c_settings.h file.
Returns
TRUE if a transfer is in progress, false otherwise.
References FALSE, and USCIB0.
uint16_t bitSwap (uint8_t msb, uint8_t lsb)
Simple function to take two bytes and combine them into one word. This is useful for HIDI2C because everything comes in from the host MSB first
Parameters
msb Most significant byte of data
lsb Least significant byte of data
Referenced by handleHIDCommand(), and hidI2C_handleData().
Copyright 2013, Texas Instruments Incorporated