i2c_engine_usci_init.c File Reference
i2c_engine_usci_init.c File Reference
Detailed Description
Contains all of the initialization functions and structures for the I2C layer of the HIDI2C stack. ifdefs are used to minimize the memory footprint for users not using multiple devices. Specific USCI settings are defined in the hidi2c_settings.h file.
#include <hidi2c_types.h>
#include <i2c_engine_usci_init.h>
#include <hidi2c_settings.h>
#include <msp430.h>
Functions
BOOL hidI2C_initializeUSCII2C (BOOL idle)
void hidI2C_setGPIOPinIdle (uint8_t interface)
void hidI2C_setGPIOPinActive (uint8_t interface)
Function Documentation
BOOL hidI2C_initializeUSCII2C (BOOL idle)
References TRUE.
Referenced by hidI2C_initializeI2C().
void hidI2C_setGPIOPinIdle (uint8_t interface)
Sets the GPIO pin for the given interface in idle state. Accounts for the ACTIVE_LOW setting defined in hidi2c_settings.h file.
Parameters
interface Specific interface to set the GPIO pin for as defined in the hidi2c_settings.h file.
References USCIB0, USCIB0_GPIO_PDIR, and USCIB0_GPIO_PIN.
void hidI2C_setGPIOPinActive (uint8_t interface)
Sets the GPIO pin for the given interface in active state. Accounts for the ACTIVE_LOW setting defined in hidi2c_settings.h file.
Parameters
interface Specific interface to set the GPIO pin for as defined in the hidi2c_settings.h file.
References USCIB0, USCIB0_GPIO_PDIR, and USCIB0_GPIO_PIN.
Referenced by hidI2C_setDataAndInitializeInterrupt(), queueResetReport(), and setInputReportAndInitiateSend().
Copyright 2013, Texas Instruments Incorporated