main.c File Reference
mouse/main.c File Reference
#include "hidi2c_types.h"
#include "mouse_descriptors.h"
#include "hid_engine.h"
#include "hidi2c_settings.h"
#include "msp430.h"
Functions
int main (void)
BOOL outputReportEventHandler (uint8_t interface, uint8_t *data)
BOOL goToSleepEventHandler ()
BOOL wakeUpEventHandler ()
uint8_t * handleGetReportCalled (uint8_t interface, uint8_t reportid)
BOOL handleSetReportCalled (uint8_t interface, uint8_t reportid, uint8_t *feature)
__interrupt void TIMER0_A0_ISR (void)
Variables
MOUSE_REPORT mouseReport = { 0, 0, 0, 0 }
const int tableSinCosLookUp [93][2]
uint8_t index = 1
uint8_t sendNewMousePosition = FALSE
volatile BOOL gotoSleep = FALSE
Function Documentation
int main (void)
References HidI2CSetting::bInterface, MOUSE_REPORT::dX, MOUSE_REPORT::dY, gotoSleep, index, initializeHidI2CStack(), HidI2CSetting::pReportDescriptor, report_desc_HID0, sendNewMousePosition, setInputReportAndInitiateSend(), tableSinCosLookUp, USCIB0, and HidI2CSetting::wReportLength.
BOOL outputReportEventHandler (uint8_t interface, uint8_t * data)
Output report handler.
Returns
TRUE if the user wants to clear LPM bits after this interrupt, FALSE if the user wants the LPM bits not to be touched \
References FALSE.
Referenced by handleHIDCommand(), and hidI2C_handleData().
BOOL goToSleepEventHandler ()
Event handlers that are called when the host receives a command to put the device to sleep or wake it up. It is important to note that these handlers are called in interrupt context and should be very brief in nature (set a flag
Returns
TRUE if the user wants to clear LPM bits after this interrupt, FALSE if the user wants the LPM bits not to be touched
References gotoSleep, and TRUE.
Referenced by handleHIDCommand().
BOOL wakeUpEventHandler ()
Because LPM bits need to be cleared at the end of the calling interrupt. Returning TRUE from this function will clear the LPM bits on the MSP430 and cause it to wake up from sleep.
Returns
TRUE if the user wants to clear LPM bits after this interrupt, FALSE if the user wants the LPM bits not to be touched
References FALSE, gotoSleep, and TRUE.
Referenced by handleHIDCommand().
uint8_t* handleGetReportCalled (uint8_t interface, uint8_t reportid)
Grabs the latest input report from the device.
Returns
uint8_t* Pointer to array with the latest input report.
References mouseReport.
Referenced by handleHIDCommand().
BOOL handleSetReportCalled (uint8_t interface, uint8_t reportid, uint8_t * feature)
Event handler called when a SET_REPORT command is issued by the host. For keyboards/mice, feature reports are not supported so this is a dummy handler
Parameters
interface Specific interface being used
reportid Report ID of the feature report that was set
feature New feature report
Returns
TRUE if the user wants to clear LPM bits after this interrupt, FALSE if the user wants the LPM bits not to be touched
References FALSE.
Referenced by handleHIDCommand().
__interrupt void TIMER0_A0_ISR (void)
References sendNewMousePosition, and TRUE.
Variable Documentation
MOUSE_REPORT mouseReport = { 0, 0, 0, 0 }
Referenced by handleGetReportCalled().
const int tableSinCosLookUp[93][2]
Referenced by main().
uint8_t index = 1
Referenced by handleHIDCommand(), main(), setFeatureReport(), and setInputReportAndInitiateSend().
uint8_t sendNewMousePosition = FALSE
Referenced by main(), and TIMER0_A0_ISR().
volatile BOOL gotoSleep = FALSE
Copyright 2013, Texas Instruments Incorporated